//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tweet_reference")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub source_tweet_id: i32,
    pub reference_type: String,
    pub reference_tweet_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tweet::Entity",
        from = "Column::ReferenceTweetId",
        to = "super::tweet::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tweet2,
    #[sea_orm(
        belongs_to = "super::tweet::Entity",
        from = "Column::SourceTweetId",
        to = "super::tweet::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tweet1,
}

impl ActiveModelBehavior for ActiveModel {}
